MakeCode102.agentAnalyze(SixDirection.Forward);
MakeCode102.agentDetectDryFern(SixDirection.Forward);
MakeCode102.agentDetectDryGrass(SixDirection.Forward);
MakeCode102.agentDetectDryBrush(SixDirection.Forward);
MakeCode102.hazardsRemainL4();
MakeCode102.hazardsRemainL5();
MakeCode102.hazardsRemainL6();
MakeCode102.agentDestroyL4(SixDirection.Forward);
MakeCode102.agentDestroyL5(SixDirection.Forward);
MakeCode102.agentDestroyL6(SixDirection.Forward);
MakeCode102.ooopenDoor();
MakeCode102.sayhi();
MakeCode102.completeTask();
MakeCode102.agentLookForHazards();
MakeCode102.agentSeeHazard();
MakeCode102.alertTeam();
MakeCode102.fakePlace(Block.Grass, SixDirection.Forward);
