MakeCode.agentAnalyze(SixDirection.Forward);
MakeCode.agentDetectDryFern(SixDirection.Forward);
MakeCode.agentDetectDryGrass(SixDirection.Forward);
MakeCode.agentDetectDryBrush(SixDirection.Forward);
MakeCode.hazardsRemainL4();
MakeCode.hazardsRemainL5();
MakeCode.hazardsRemainL6();
MakeCode.agentDestroyL4(SixDirection.Forward);
MakeCode.agentDestroyL5(SixDirection.Forward);
MakeCode.agentDestroyL6(SixDirection.Forward);
MakeCode.ooopenDoor();
MakeCode.sayhi();
MakeCode.completeTask();
MakeCode.agentLookForHazards();
MakeCode.agentSeeHazard();
MakeCode.alertTeam();
MakeCode.fakePlace(Block.Grass, SixDirection.Forward);
